### ISSUE TITLE
JUnit Thread Test 에 대하여 글보고 댓글이 안달려 이슈로 남깁니다.

### ISSUE THREAD

**Issue by rkdgusrnrlrl** [nologging/nologging.github.io#2]
thread 로 병렬 처리 예제를 해보려고, junit 테스트 해보려고 검색 하다 블로그 찾았습니다.
덕분에 thread 에 여러 종료가 있다는 걸 알게되었습니다 고맙습니다 (_ _) ㅎㅎ

아직 작성중이신 것 같은데 follow 해 두고 나머지 글도 기대하고 있겠습니다. ㅎㅎ

**Comment by ors-woon** [comment]
앗 감사합니다 :D !! 
요즘 작성을 안하고 있었는데 ..  반성하게 되네요 ..
(원인 찾아보고 해결해두도록 하겠습니다 ~~! )

**Comment by ors-woon** [comment]
제 git blog에서  댓글 기능을 지원하기 위해 utterance 라는 opensource(?)를 사용하고 있었습니다.
 (utterance 서버에서) Azure가 더이상 node 버전을 지원하지 않아 발생했던 [문제](https://github.com/utterance/utterances/issues/34)로, git 관리자가 버전을 업데이트하면서 해결 되었습니다.  
현재 댓글이 정상적으로 작동하는걸 확인했습니다. 
관심(?) 감사합니다 ~~! 
추후, utternace 사용법도 업데이트할 예정인데요, 많은 관심 부탁드릴게요 ~~! ㅎ
