### ISSUE TITLE
JUnit 에서 thread Test 하기 위한 글 정리 

### ISSUE THREAD

**Issue by ors-woon** [nologging/nologging.github.io#3]
글을 쓰기 앞서, JUnit 에서 실행이 끝나면 모든 thread를 죽도록 했는지 의도를 알아야하며,
그후, thread를 테스트하기 위한 방법을 찾아야한다. 

해결 방법으로는 worker thread가 끝나기전 main Thread를 sleep 해 놓고, 마지막 worker thread가 끝날 때 main Thread를 살리는 방법이 있습니다 :D 
( 사실 이렇게까지 해서 테스트에 스레드를 써야하는가? 는 조금 애매하네요.)

https://stackoverflow.com/questions/5336251/how-do-i-write-a-junit-test-case-to-test-threads-and-events

**Comment by ors-woon** [comment]
많은 이유가 있겠지만, assert문 마다 thread가 끝나기를 기다리기도 어렵고,
현재 실행 중인 thread를 판단하기도 어려울것 같음.
(Java에서 현재 실행중인 thread 목록을 가져올 수 있나?)

간단한 XUnit 을 구현해봐도 Thread를 감안해서 설계하기는 어려울 것 같아
(몇가지 예제를 정리해보자)

**Comment by rkdgusrnrlrl** [comment]
- `Future` 를 써보면 어떨까요 `future.get()`을 하면 쓰레드가 끝난 뒤 처리 값을 받을 떄까지 대기하는 것 같습니다.
  - [Java Concurrency: Executor와 Callable/Future](http://javacan.tistory.com/entry/134)
  - [Java 8 Concurrency Tutorial: Threads and Executors](http://winterbe.com/posts/2015/04/07/java8-concurrency-tutorial-thread-executor-examples/)
- 비동기 적으로 돌아가는 녀석들을 테스트 하기가 영 까다롭네요 ㅠㅠ

**Comment by ors-woon** [comment]
넵 ~! 
" 별도의 assert 문을 만들고, 마지막 인자로 실행중인 futrue 를 받아, 작업이 끝날때 까지 block을 해버리는 함수를 만들어볼까 ? "
라는 생각을 해봤었는데요. 
이쯤에서 드는 생각은 .. Test case를 짜면서 결과값이 달라질 수 있는 (thread가 매번 같은 순서로 동작하지 않기에) Thread를 사용해야하는지 의문이 생겼습니다.

개인적인 생각이 test에서 thread 사용을 피해야한다 ! 로 좁혀지고 있는데요  :D   
혹시 다른 의견있으시면 부탁드릴게요 ~!
